package com.hd.snscoins.core;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.hd.snscoins.core.Coin;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table product.
*/
public class CoinDao extends AbstractDao<Coin, Long> {

    public static final String TABLENAME = "product";

    /**
     * Properties of entity Coin.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ResourceId = new Property(1, long.class, "resourceId", false, "RESOURCE_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Image_url = new Property(3, String.class, "image_url", false, "IMAGE_URL");
        public final static Property Image_path = new Property(4, String.class, "image_path", false, "IMAGE_PATH");
        public final static Property Id_sub_type = new Property(5, long.class, "id_sub_type", false, "ID_SUB_TYPE");
        public final static Property Bookmarked = new Property(6, Boolean.class, "bookmarked", false, "BOOKMARKED");
        public final static Property Sequence = new Property(7, String.class, "sequence", false, "SEQUENCE");
    };

    private DaoSession daoSession;

    private Query<Coin> coinSubType_CoinListQuery;

    public CoinDao(DaoConfig config) {
        super(config);
    }
    
    public CoinDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'product' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'RESOURCE_ID' INTEGER NOT NULL ," + // 1: resourceId
                "'NAME' TEXT NOT NULL ," + // 2: name
                "'IMAGE_URL' TEXT," + // 3: image_url
                "'IMAGE_PATH' TEXT," + // 4: image_path
                "'ID_SUB_TYPE' INTEGER NOT NULL ," + // 5: id_sub_type
                "'BOOKMARKED' INTEGER," + // 6: bookmarked
                "'SEQUENCE' TEXT);"); // 7: sequence
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'product'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Coin entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getResourceId());
        stmt.bindString(3, entity.getName());
 
        String image_url = entity.getImage_url();
        if (image_url != null) {
            stmt.bindString(4, image_url);
        }
 
        String image_path = entity.getImage_path();
        if (image_path != null) {
            stmt.bindString(5, image_path);
        }
        stmt.bindLong(6, entity.getId_sub_type());
 
        Boolean bookmarked = entity.getBookmarked();
        if (bookmarked != null) {
            stmt.bindLong(7, bookmarked ? 1l: 0l);
        }
 
        String sequence = entity.getSequence();
        if (sequence != null) {
            stmt.bindString(8, sequence);
        }
    }

    @Override
    protected void attachEntity(Coin entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Coin readEntity(Cursor cursor, int offset) {
        Coin entity = new Coin( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // resourceId
            cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // image_url
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // image_path
            cursor.getLong(offset + 5), // id_sub_type
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // bookmarked
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // sequence
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Coin entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setResourceId(cursor.getLong(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setImage_url(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setImage_path(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setId_sub_type(cursor.getLong(offset + 5));
        entity.setBookmarked(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setSequence(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Coin entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Coin entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "coinList" to-many relationship of CoinSubType. */
    public List<Coin> _queryCoinSubType_CoinList(long id_sub_type) {
        synchronized (this) {
            if (coinSubType_CoinListQuery == null) {
                QueryBuilder<Coin> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id_sub_type.eq(null));
                coinSubType_CoinListQuery = queryBuilder.build();
            }
        }
        Query<Coin> query = coinSubType_CoinListQuery.forCurrentThread();
        query.setParameter(0, id_sub_type);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCoinSubTypeDao().getAllColumns());
            builder.append(" FROM product T");
            builder.append(" LEFT JOIN sub_type T0 ON T.'ID_SUB_TYPE'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Coin loadCurrentDeep(Cursor cursor, boolean lock) {
        Coin entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CoinSubType coinSubType = loadCurrentOther(daoSession.getCoinSubTypeDao(), cursor, offset);
         if(coinSubType != null) {
            entity.setCoinSubType(coinSubType);
        }

        return entity;    
    }

    public Coin loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Coin> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Coin> list = new ArrayList<Coin>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Coin> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Coin> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
