package com.hd.snscoins.core;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table news.
 */
public class News {

    private Long id;
    /** Not-null value. */
    private String title;
    private String date;
    private String time;
    private String details;
    private String img_path;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public News() {
    }

    public News(Long id) {
        this.id = id;
    }

    public News(Long id, String title, String date, String time, String details, String img_path) {
        this.id = id;
        this.title = title;
        this.date = date;
        this.time = time;
        this.details = details;
        this.img_path = img_path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public String getImg_path() {
        return img_path;
    }

    public void setImg_path(String img_path) {
        this.img_path = img_path;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
